Create Table If Not Exists `user`(
	id INT NOT NULL AUTO_INCREMENT COMMENT '编号',
	name VARCHAR(50) NOT NULL DEFAULT '' COMMENT '名称。登录用户名',
	password VARCHAR(200) COMMENT '密码',
	displayname VARCHAR(50) COMMENT '昵称',
	sex INT NOT NULL DEFAULT 0 COMMENT '性别。未知、男、女',
	mail VARCHAR(50) COMMENT '邮件。支持登录',
	mailverified TINYINT NOT NULL DEFAULT 0 COMMENT '邮箱验证。邮箱是否已通过验证',
	mobile VARCHAR(50) COMMENT '手机。支持登录',
	mobileverified TINYINT NOT NULL DEFAULT 0 COMMENT '手机验证。手机是否已通过验证',
	code VARCHAR(50) COMMENT '代码。身份证、员工编码等，支持登录',
	areaid INT NOT NULL DEFAULT 0 COMMENT '地区。省市区',
	avatar VARCHAR(200) COMMENT '头像',
	roleid INT NOT NULL DEFAULT 3 COMMENT '角色。主要角色',
	roleids VARCHAR(200) COMMENT '角色组。次要角色集合',
	departmentid INT NOT NULL DEFAULT 0 COMMENT '部门。组织机构',
	online TINYINT NOT NULL DEFAULT 0 COMMENT '在线',
	enable TINYINT NOT NULL DEFAULT 0 COMMENT '启用',
	age INT NOT NULL DEFAULT 0 COMMENT '年龄。周岁',
	birthday DATETIME COMMENT '生日。公历年月日',
	logins INT NOT NULL DEFAULT 0 COMMENT '登录次数',
	lastlogin DATETIME COMMENT '最后登录',
	lastloginip VARCHAR(50) COMMENT '最后登录IP',
	registertime DATETIME COMMENT '注册时间',
	registerip VARCHAR(50) COMMENT '注册IP',
	onlinetime INT NOT NULL DEFAULT 0 COMMENT '在线时间。累计在线总时间，单位秒',
	ex1 INT NOT NULL DEFAULT 0 COMMENT '扩展1',
	ex2 INT NOT NULL DEFAULT 0 COMMENT '扩展2',
	ex3 DOUBLE NOT NULL DEFAULT 0 COMMENT '扩展3',
	ex4 VARCHAR(50) COMMENT '扩展4',
	ex5 VARCHAR(50) COMMENT '扩展5',
	ex6 VARCHAR(50) COMMENT '扩展6',
	updateuser VARCHAR(50) NOT NULL DEFAULT '' COMMENT '更新者',
	updateuserid INT NOT NULL DEFAULT 0 COMMENT '更新用户',
	updateip VARCHAR(50) COMMENT '更新地址',
	updatetime DATETIME NOT NULL DEFAULT '0001-01-01' COMMENT '更新时间',
	remark VARCHAR(500) COMMENT '备注',
	Primary Key (id)
) DEFAULT CHARSET=utf8mb4;