Create Table [user](
	id int IDENTITY(1,1) Primary Key,
	name nvarchar(50) NOT NULL DEFAULT '',
	password nvarchar(200) NULL,
	displayname nvarchar(50) NULL,
	sex int NOT NULL DEFAULT 0,
	mail nvarchar(50) NULL,
	mailverified bit NOT NULL DEFAULT 0,
	mobile nvarchar(50) NULL,
	mobileverified bit NOT NULL DEFAULT 0,
	code nvarchar(50) NULL,
	areaid int NOT NULL DEFAULT 0,
	avatar nvarchar(200) NULL,
	roleid int NOT NULL DEFAULT 3,
	roleids nvarchar(200) NULL,
	departmentid int NOT NULL DEFAULT 0,
	[online] bit NOT NULL DEFAULT 0,
	enable bit NOT NULL DEFAULT 0,
	age int NOT NULL DEFAULT 0,
	birthday datetime NULL,
	logins int NOT NULL DEFAULT 0,
	lastlogin datetime NULL,
	lastloginip nvarchar(50) NULL,
	registertime datetime NULL,
	registerip nvarchar(50) NULL,
	onlinetime int NOT NULL DEFAULT 0,
	ex1 int NOT NULL DEFAULT 0,
	ex2 int NOT NULL DEFAULT 0,
	ex3 float NOT NULL DEFAULT 0,
	ex4 nvarchar(50) NULL,
	ex5 nvarchar(50) NULL,
	ex6 nvarchar(50) NULL,
	updateuser nvarchar(50) NOT NULL DEFAULT '',
	updateuserid int NOT NULL DEFAULT 0,
	updateip nvarchar(50) NULL,
	updatetime datetime NOT NULL DEFAULT '0001-01-01',
	remark nvarchar(500) NULL
)